# Extensions for reusable configurations
x-common-variables: &common-variables
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}
  UMASK: 002

x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-file: ${DOCKERLOGGING_MAXFILE}
      max-size: ${DOCKERLOGGING_MAXSIZE}

x-pullio-labels: &pullio-labels
  org.hotio.pullio.update: ${PULLIO_UPDATE}
  org.hotio.pullio.notify: ${PULLIO_NOTIFY}
  org.hotio.pullio.discord.webhook: ${PULLIO_DISCORD_WEBHOOK}

x-tsbridge-labels: &tsbridge-labels
  tsbridge.enabled: "true"


x-restart-policy: &restart-policy
  restart: unless-stopped

# Complete service base configurations
x-base-service: &base-service
  <<: [*restart-policy, *default-logging]

x-servarr-service: &servarr-service
  <<: *base-service
  environment:
    <<: *common-variables

services:
  # tsbridge for Tailscale access
  tsbridge:
    image: ghcr.io/jtdowney/tsbridge:latest
    container_name: tsbridge
    <<: *base-service
    command: ["--provider", "docker"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERCONFDIR}/tsbridge:/var/lib/tsbridge
    environment:
      - TS_OAUTH_CLIENT_ID=${TS_OAUTH_CLIENT_ID}
      - TS_OAUTH_CLIENT_SECRET=${TS_OAUTH_CLIENT_SECRET}
    labels:
      - "tsbridge.tailscale.oauth_client_id_env=TS_OAUTH_CLIENT_ID"
      - "tsbridge.tailscale.oauth_client_secret_env=TS_OAUTH_CLIENT_SECRET"
      - "tsbridge.tailscale.state_dir=/var/lib/tsbridge"
      - "tsbridge.tailscale.default_tags=tag:server" # Must match or be owned by your OAuth client's tag
        

  # Radarr - https://hotio.dev/containers/radarr/
  # sudo -u docker mkdir -m=00775 /volume1/docker/appdata/radarr
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    <<: *servarr-service
    ports:
      - 7878:7878
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/data
      - torrents-hbd-nvme:/torrents-nvme:ro
      - torrents-hbd-hdd:/torrents-hdd:ro

  # 4K Radarr instance. Same as above but only for 4k/UHD Movies
  4kradarr:
    container_name: 4kradarr
    image: ghcr.io/hotio/radarr:latest
    <<: *servarr-service
    ports:
      - 7877:7878
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "7878"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/4kradarr:/config
      - ${DOCKERSTORAGEDIR}:/data
      - torrents-hbd-nvme:/torrents-nvme:ro
      - torrents-hbd-hdd:/torrents-hdd:ro

  # Sonarr - https://hotio.dev/containers/sonarr/
  # sudo -u docker mkdir -m=00775 /volume1/docker/appdata/sonarr
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr:nightly
    <<: *servarr-service
    ports:
      - 8989:8989
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/data
      - torrents-hbd-nvme:/torrents-nvme:ro
      - torrents-hbd-hdd:/torrents-hdd:ro

  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    <<: *servarr-service
    ports:
      - 9696:9696
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "9696"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/prowlarr:/config
      - ${DOCKERSTORAGEDIR}:/data
      - torrents-hbd-nvme:/torrents-nvme:ro
      - torrents-hbd-hdd:/torrents-hdd:ro

  # Overseerr - https://hotio.dev/containers/overseerr/
  # sudo -u docker mkdir -m=00775 /volume1/docker/appdata/overseerr
  overseerr:
    container_name: overseerr
    image: ghcr.io/hotio/overseerr:latest
    <<: *servarr-service
    ports:
      - 5055:5055
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "5055"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/overseerr:/config

  # Bazarr - https://hotio.dev/containers/bazarr/
  # sudo -u docker mkdir -m=00775 /volume1/docker/appdata/bazarr
  bazarr:
    container_name: bazarr
    image: ghcr.io/hotio/bazarr:latest
    <<: *servarr-service
    ports:
      - 6767:6767
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "6767"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSTORAGEDIR}/media:/data/media
      - torrents-hbd-nvme:/torrents-nvme:ro
      - torrents-hbd-hdd:/torrents-hdd:ro

  # upgraderr - https://github.com/kylesanderson/upgraderr
  upgraderr:
    container_name: upgraderr
    image: ghcr.io/kylesanderson/upgraderr:main
    <<: *base-service
    ports:
      - 6940:6940
    user: ${PUID}:${PGID}
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "6940"
    environment:
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro

  # autobrr - https://autobrr.com
  # sudo -u docker mkdir -m=00775 /volume1/docker/appdata/autobrr
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    <<: *base-service
    ports:
      - 7474:7474
    user: ${PUID}:${PGID}
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "7474"
    environment:
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/autobrr:/config:rw

  # Plex - https://hotio.dev/containers/plex/
  # sudo -u docker mkdir -m=00775 -p /volume1/docker/appdata/plex
  # Also please read the extra info => https://trash-guides.info/Hardlinks/How-to-setup-for/Synology/#appdata
  plex:
    container_name: plex
    image: ghcr.io/hotio/plex:latest
    <<: *base-service
    ports:
      - 32400:32400
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "32400"
    environment:
      <<: *common-variables
      ARGS:
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${PLEX_ADVERTISE_IP}
      ALLOWED_NETWORKS:
      PLEX_PASS: ${PLEX_PASS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/plex:/config:rw
      - ${DOCKERSTORAGEDIR}/media:/data/media:rw
      - ${DOCKERSTORAGEDIR}/transcodes:/transcode:rw # If you want to have transcodes live in RAM consider the below options
    devices: # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass) uncomment this line.
      - /dev/dri:/dev/dri # optional: if you have a Syno with an Intel CPU with quicksync and want hardware transcoding (only with Plex Pass) uncomment this line.
  #    tmpfs:                                          # optional: if you have a Syno with enough RAM, you can uncomment this line to enable transcoding in RAM. uncomment this line.
  #      - /transcode                                  # optional: if you have a Syno with enough RAM, you can uncomment this line to enable transcoding in RAM. uncomment this line.

  # Tautulli - https://hotio.dev/containers/tautulli/
  # sudo -u docker mkdir -m=00775 -p /volume1/docker/appdata/tautulli
  tautulli:
    container_name: tautulli
    image: ghcr.io/hotio/tautulli:latest
    <<: *servarr-service
    ports:
      - 8181:8181
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "8181"
    environment:
      <<: *common-variables
      WEBUI_PORTS: 8181/tcp,8181/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/tautulli:/config:rw

  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    <<: *base-service
    ports:
      - 5454:5454
    user: ${PUID}:${PGID}
    labels:
      <<: [*pullio-labels, *tsbridge-labels]
      tsbridge.service.port: "5454"
    environment:
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/notifiarr:/config

# Native NFS Volume Definitions
volumes:
  torrents-hbd-nvme:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${REMOTE_HOST},nfsvers=4,rsize=1048576,wsize=1048576,timeo=600,retrans=2,hard,intr
      device: "/home/fizzy/torrents/qbittorrent"

  torrents-hbd-hdd:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${REMOTE_HOST},nfsvers=4,rsize=1048576,wsize=1048576,timeo=600,retrans=2,hard,intr
      device: "/home/fizzy/storage/qbittorrent"
